version: '3.8'

services:

  coffee-counter:
    build: .
    container_name: coffee-counter-app
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - APP_URL=https://${DOMAIN:-localhost}
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=database
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coffee-counter.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.coffee-counter.tls=true"
      - "traefik.http.routers.coffee-counter.tls.certresolver=letsencrypt"
      - "traefik.http.routers.coffee-counter.entrypoints=websecure"
      - "traefik.http.services.coffee-counter.loadbalancer.server.port=80"
      - "traefik.http.routers.coffee-counter-insecure.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.coffee-counter-insecure.entrypoints=web"
      - "traefik.http.routers.coffee-counter-insecure.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - traefik
    depends_on:
      - traefik

networks:
  traefik:
    external: false
